In [1]:
import sys
from pathlib import Path
import logging

project_root = Path.cwd().parent
sys.path.append(str(project_root))

logging.getLogger().setLevel(logging.WARNING)

In [2]:
#PAYROLL
from src.config import CONFIG
from src.ingestion import ingest_all_sources
ingest= ingest_all_sources(CONFIG["input_dir"])
df=ingest["globaltech_hris"]

df["employment_type"].unique()
#df.head(5)

2026-06-03 08:27:47,073 [INFO] Starting ingestion of all source systems
2026-06-03 08:27:47,075 [INFO] Ingesting globaltech hris csv: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\globaltech_hris.csv
2026-06-03 08:27:47,154 [INFO] Ingested 15000 records from globaltech hris CSV
2026-06-03 08:27:47,156 [INFO] Ingesting AcquiredCo API JSON: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\acquiredco_api.json
2026-06-03 08:27:47,198 [INFO] Processed AcquiredCo page 1
2026-06-03 08:27:47,214 [INFO] Processed AcquiredCo page 2
2026-06-03 08:27:47,227 [INFO] Processed AcquiredCo page 3
2026-06-03 08:27:47,240 [INFO] Processed AcquiredCo page 4
2026-06-03 08:27:47,254 [INFO] Processed AcquiredCo page 5
2026-06-03 08:27:47,267 [INFO] Processed AcquiredCo page 6
2026-06-03 08:27:47,278 [INFO] Processed AcquiredCo page 7
2026-06-03 08:27:47,318 [INFO] Ingested 3200 AcquiredCo records
2026-06-03 08:27:47,322 [INFO] Ingesting payroll data: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\payroll_data.xlsx
2026-06-03 08:27:49,954 [INFO] Removed 500 duplicate payroll rows
2026-06-03 08:27:49,956 [INFO] Loaded 18500 payroll records
2026-06-03 08:27:49,957 [INFO] Ingesting benefits XML: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\benefits_enrollment.xml
2026-06-03 08:27:50,088 [INFO] Loaded 12000 benefits enrollment records
2026-06-03 08:27:50,105 [INFO] Completed ingestion for all datasets

<ArrowStringArray>
['Full-Time', 'Contractor', 'Part-Time']
Length: 3, dtype: str

In [ ]:
from src.cleaning import clean_acquiredco_noise,namespace_employee_ids
#AquiredCo
ingest= ingest_all_sources(CONFIG["input_dir"])
df=ingest["acquiredco_hris"]
df=clean_acquiredco_noise(df)
df=namespace_employee_ids(df,"AC")
df.head(5)

#df.head(5)

2026-06-03 08:31:37,617 [INFO] Starting ingestion of all source systems
2026-06-03 08:31:37,618 [INFO] Ingesting globaltech hris csv: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\globaltech_hris.csv
2026-06-03 08:31:37,701 [INFO] Ingested 15000 records from globaltech hris CSV
2026-06-03 08:31:37,703 [INFO] Ingesting AcquiredCo API JSON: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\acquiredco_api.json
2026-06-03 08:31:37,754 [INFO] Processed AcquiredCo page 1
2026-06-03 08:31:37,778 [INFO] Processed AcquiredCo page 2
2026-06-03 08:31:37,801 [INFO] Processed AcquiredCo page 3
2026-06-03 08:31:37,822 [INFO] Processed AcquiredCo page 4
2026-06-03 08:31:37,842 [INFO] Processed AcquiredCo page 5
2026-06-03 08:31:37,859 [INFO] Processed AcquiredCo page 6
2026-06-03 08:31:37,875 [INFO] Processed AcquiredCo page 7
2026-06-03 08:31:37,885 [INFO] Ingested 3200 AcquiredCo records
2026-06-03 08:31:37,890 [INFO] Ingesting payroll data: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\payroll_data.xlsx
2026-06-03 08:31:40,388 [INFO] Removed 500 duplicate payroll rows
2026-06-03 08:31:40,390 [INFO] Loaded 18500 payroll records
2026-06-03 08:31:40,390 [INFO] Ingesting benefits XML: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\benefits_enrollment.xml
2026-06-03 08:31:40,509 [INFO] Loaded 12000 benefits enrollment records
2026-06-03 08:31:40,524 [INFO] Completed ingestion for all datasets

3000

In [ ]:
#PAYROLL
ingest= ingest_all_sources(CONFIG["input_dir"])
df=ingest["payroll"]

df["pay_frequency"].unique()
#df.head(5)

2026-06-03 08:27:53,236 [INFO] Starting ingestion of all source systems
2026-06-03 08:27:53,237 [INFO] Ingesting globaltech hris csv: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\globaltech_hris.csv
2026-06-03 08:27:53,307 [INFO] Ingested 15000 records from globaltech hris CSV
2026-06-03 08:27:53,309 [INFO] Ingesting AcquiredCo API JSON: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\acquiredco_api.json
2026-06-03 08:27:53,340 [INFO] Processed AcquiredCo page 1
2026-06-03 08:27:53,354 [INFO] Processed AcquiredCo page 2
2026-06-03 08:27:53,367 [INFO] Processed AcquiredCo page 3
2026-06-03 08:27:53,380 [INFO] Processed AcquiredCo page 4
2026-06-03 08:27:53,393 [INFO] Processed AcquiredCo page 5
2026-06-03 08:27:53,406 [INFO] Processed AcquiredCo page 6
2026-06-03 08:27:53,415 [INFO] Processed AcquiredCo page 7
2026-06-03 08:27:53,421 [INFO] Ingested 3200 AcquiredCo records
2026-06-03 08:27:53,425 [INFO] Ingesting payroll data: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\payroll_data.xlsx
2026-06-03 08:27:55,699 [INFO] Removed 500 duplicate payroll rows
2026-06-03 08:27:55,700 [INFO] Loaded 18500 payroll records
2026-06-03 08:27:55,702 [INFO] Ingesting benefits XML: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\benefits_enrollment.xml
2026-06-03 08:27:55,846 [INFO] Loaded 12000 benefits enrollment records
2026-06-03 08:27:55,861 [INFO] Completed ingestion for all datasets

,employee_id,source,base_salary,currency,pay_frequency,bonus_target_pct,effective_date
0,14571,payroll,77935,EUR,Monthly,24.5,2023-05-12
1,12628,payroll,119344,EUR,Bi-Weekly,2.8,2024-08-02
2,12173,payroll,67963,GBP,Annual,5.9,2023-10-12
3,8747,payroll,101292,EUR,Monthly,17.9,2023-06-15
4,1729,payroll,95986,GBP,Monthly,26.6,2023-06-28

In [5]:
#PAYROLL
ingest= ingest_all_sources(CONFIG["input_dir"])
df=ingest["benefits"]

#df["source"].unique()
df.head(5)

2026-06-03 08:27:55,888 [INFO] Starting ingestion of all source systems
2026-06-03 08:27:55,890 [INFO] Ingesting globaltech hris csv: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\globaltech_hris.csv
2026-06-03 08:27:55,950 [INFO] Ingested 15000 records from globaltech hris CSV
2026-06-03 08:27:55,952 [INFO] Ingesting AcquiredCo API JSON: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\acquiredco_api.json
2026-06-03 08:27:55,986 [INFO] Processed AcquiredCo page 1
2026-06-03 08:27:56,000 [INFO] Processed AcquiredCo page 2
2026-06-03 08:27:56,014 [INFO] Processed AcquiredCo page 3
2026-06-03 08:27:56,029 [INFO] Processed AcquiredCo page 4
2026-06-03 08:27:56,042 [INFO] Processed AcquiredCo page 5
2026-06-03 08:27:56,054 [INFO] Processed AcquiredCo page 6
2026-06-03 08:27:56,064 [INFO] Processed AcquiredCo page 7
2026-06-03 08:27:56,070 [INFO] Ingested 3200 AcquiredCo records
2026-06-03 08:27:56,076 [INFO] Ingesting payroll data: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\payroll_data.xlsx
2026-06-03 08:27:58,380 [INFO] Removed 500 duplicate payroll rows
2026-06-03 08:27:58,382 [INFO] Loaded 18500 payroll records
2026-06-03 08:27:58,383 [INFO] Ingesting benefits XML: c:\Users\JudeNyahe\Desktop\hr-integration-pipeline\data\raw\benefits_enrollment.xml
2026-06-03 08:27:58,500 [INFO] Loaded 12000 benefits enrollment records
2026-06-03 08:27:58,516 [INFO] Completed ingestion for all datasets

,employee_id,plan_type,coverage_level,enrollment_date,premium_employee,premium_employer,source
0,2239,Vision,Family,2024-03-23,54.50,469.17,benefits
1,7612,401(k),Employee+Spouse,2021-06-14,188.19,705.57,benefits
2,12967,Life Insurance,Employee+Child,2020-07-26,63.50,261.07,benefits
3,12133,Health Insurance,Employee+Child,2024-05-25,213.74,875.07,benefits
4,14962,Life Insurance,Individual,2024-08-04,272.75,911.80,benefits